### ISSUE TITLE
Starting bot

### ISSUE THREAD

**Issue by Re5pawn404** [Vislate/DayZ-Console-Killfeed#3]
Hi Locvic,

Not sure if you can help but when I try to start the bot I get an error regarding "intents" in the main.py file,

Is there something I'm missing or something changed in the code?

Thanks.

**Comment by jonesph** [comment]
Same issue.  Here is the actual error message.
Traceback (most recent call last):
  File "/usr/src/bot/main.py", line 64, in <module>
    main()
  File "/usr/src/bot/main.py", line 36, in main
    bot = commands.Bot(
          ^^^^^^^^^^^^^
TypeError: BotBase.__init__() missing 1 required keyword-only argument: 'intents'

**Comment by kilgoreandy** [comment]
This is basic discord python syntax. 

You have to enable intents both online and in your code. 

In your code it should look something like this 

intents = discord.Intents().all()
bot = discord.Bot(intents=intents, help_command=None, command_prefix='$')
